name: Model Template
description: Add/ Modify a model
title: "[New Feature]: "
labels: ["enhancement"]
projects: ["Colib0"]
assignees:
  - GJCRESYM
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!   
  - type: checkboxes
    attributes:
      label: Do you want to add a new model or modify an existing model?
      description: Specifiy if its a new model or request for modification
      options:
        - label: New Model
        - label: Modify an existing model
    validations:
      required: true      
  - type: input
    id: Model name
    attributes:
      label: Model Name
      description: Name the model you would like to modify?
      placeholder: ex. HVDC_VSC HVDC Model
    validations:
      required: false
  - type: textarea
    id: Current-Behaviour
    attributes:
      label: Describe the current behaviour
      description: What is the current behaviour?
      placeholder: Tell us what you see!
      value: "Expected this instead of that!"
    validations:
      required: true
  - type: textarea
    id: Expected-Behaviour
    attributes:
      label: Describe the expected behaviour
      description: What is the expected behaviour?
      placeholder: Tell us what you see!
      value: "Display the expected result!"
    validations:
      required: false 
  - type: textarea
    id: Steps-Reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behaviour!
      placeholder: Steps to reproduce
      value: |
        1. Go to
        2. Click on
        3. Enter ...
        # Add more steps here,
    validations:
      required: false 

