name: Add Model/Test Cases Template
description: Add a model or a Test Case
title: "[Model/ Test case Name]: "
labels: ["enhancement"]
projects: ["Colib0"]
assignees:
  - GJCRESYM
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!   
  - type: checkboxes
    attributes:
      label: Do you want to add a new model or test case?
      description: |
        Specifiy if its:
          * a new model 
          * a test case
      options:
        - label: New Model
        - label: Test Cases
    validations:
      required: true      
  - type: input
    id: Name
    attributes:
      label: Name the model/ test cases you would like to add
      description: model/test case 
      placeholder: ex. HVDC_VSC HVDC Model
    validations:
      required: false
  - type: textarea
    id: Expected-Behaviour
    attributes:
      label: Briefly describe about the contribution
      description: Explain about new model/test case
      placeholder: Tell us what you see!
      value: "Describe about the contribution"
    validations:
      required: true


