name: Evaluate Model/Testcase Template
description: Evaluate a model or a Testcase
title: "[Enhancement]: "
labels: ["enhancement", "bug"]
projects: ["Colib0"]
assignees:
  - GJCRESYM
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: checkboxes
    attributes:
      label: Specify the model/testcase you evaulated
      options:
        - label: Model
        - label: Testcase
    validations:
      required: true  
  - type: input
    id: Name
    attributes:
      label: Name the model/testcase you would like to evaluate
      description: model/test cases 
      placeholder: ex. HVDC_VSC HVDC Model
    validations:
      required: true   
  - type: checkboxes
    attributes:
      label: What is the impact to the model or testcase?
      description: Specifiy if its a major change or not!
      options:
        - label: minor
        - label: moderate
        - label: major
    validations:
      required: true  
  - type: textarea
    id: Expected-Behaviour
    attributes:
      label: Briefly describe your opinion about the model/testcase
      description: Describe the modification
      placeholder: Tell us what you see!
      value: "Provide your feedback here!"
    validations:
      required: true


