name: Modify Model/Test Cases Template
description: Modify a model or a Test Cases
title: "[Enhancement]: "
labels: ["enhancement"]
projects: ["Colib0"]
assignees:
  - GJCRESYM
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!   
  - type: checkboxes
    attributes:
      label: Do you want to modify a new model or test cases?
      description: Specifiy if its a new model or test cases
      options:
        - label: New Model
        - label: Test Cases
    validations:
      required: true      
  - type: input
    id: Name
    attributes:
      label: Name the model/ test cases you would like to modify
      description: model/test cases 
      placeholder: ex. HVDC_VSC HVDC Model
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: What is the impact of modification to the new model or test cases?
      description: Specifiy if its a major change or not!
      options:
        - label: minor
        - label: moderate
        - label: major
    validations:
      required: true
  - type: textarea
    id: Expected-Behaviour
    attributes:
      label: Briefly describe about the contribution
      description: Explain about new model/test cases
      placeholder: Tell us what you see!
      value: "Describe about the contribution"
    validations:
      required: true


