name: Bug Report- COLib Website
description: File a bug report about COLib website
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["Colib0"]
assignees:
  - GJCRESYM
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: Current-Behaviour
    attributes:
      label: Describe the current behaviour
      description: What is the current behaviour?
      placeholder: Tell us what you see!
      value: "Expected this instead of that!"
    validations:
      required: true
  - type: textarea
    id: Expected-Behaviour
    attributes:
      label: Describe the expected behaviour
      description: What is the expected behaviour?
      placeholder: Tell us what you see!
      value: "Display the expected result!"
    validations:
      required: false 
  - type: textarea
    id: Steps-Reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behaviour!
      placeholder: Steps to reproduce
      value: |
        1. Go to
        2. Click on
        3. Enter ...
        # Add more steps here,
    validations:
      required: false 
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true